// generated by Fast Light User Interface Designer (fluid) version 1.0011

#include "HelpPageUI.h"

inline void HelpPageUI::cb_OK_i(Fl_Button*, void*) {
  hide();
}
void HelpPageUI::cb_OK(Fl_Button* o, void* v) {
  ((HelpPageUI*)(o->parent()->user_data()))->cb_OK_i(o,v);
}

HelpPageUI::HelpPageUI() {
  Fl_Window* w;
  { Fl_Window* o = mainWindow = new Fl_Window(390, 366, "About my image filter :)");
    w = o;
    o->user_data((void*)(this));
    { Fl_Output* o = helpText = new Fl_Output(0, 25, 390, 305, "     How to ...");
      o->type(4);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Button* o = new Fl_Button(130, 335, 135, 25, "OK");
      o->callback((Fl_Callback*)cb_OK);
    }
    o->end();
  }
}

void HelpPageUI::show() {
  mainWindow->show();
}

void HelpPageUI::hide() {
  mainWindow->hide();
}
