// generated by Fast Light User Interface Designer (fluid) version 1.0011

#ifndef BrushConfigUI_h
#define BrushConfigUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include "imgflt.h"
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Button.H>

class BrushConfigUI {
public:
  BrushConfigUI();
  Fl_Window *mainWindow;
  /*Fl_Round_Button *round;
private:
  inline void cb_round_i(Fl_Round_Button*, void*);
  static void cb_round(Fl_Round_Button*, void*);
public:
  Fl_Check_Button *square;
private:
  inline void cb_square_i(Fl_Check_Button*, void*);
  static void cb_square(Fl_Check_Button*, void*);*/
public:
  Fl_Value_Slider *brushSize;
private:
  inline void cb_brushSize_i(Fl_Value_Slider*, void*);
  static void cb_brushSize(Fl_Value_Slider*, void*);
public:
  Fl_Value_Slider *brushOpacity;
private:
  inline void cb_brushOpacity_i(Fl_Value_Slider*, void*);
  static void cb_brushOpacity(Fl_Value_Slider*, void*);
  inline void cb_Clean_i(Fl_Button*, void*);
  static void cb_Clean(Fl_Button*, void*);
  inline void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
public:
  ImgView *imgView;
  void show();
  void hide();
};
#endif
